config:
  runStrategy:
    runs: 1
    maxSecondsBetweenRuns: 30
    minSecondsBetweenRuns: 1
scenarios:
  - name: "delete prometheus pods"
    steps:
    - podAction:
        matches:
          - labels:
              namespace: "openshift-monitoring"
              selector: "app=prometheus"

        filters:
          - randomSample:
              size: 1

        # The actions will be executed in the order specified
        actions:
          - kill:
              probability: 1
              force: true
    - podAction:
        matches:
          - labels:
              namespace: "openshift-monitoring"
              selector: "app=prometheus"
        retries:
          retriesTimeout:
            timeout: 180

        actions:
          - checkPodCount:
              count: 2
